packageExtensions:
  'prism-react-renderer@*':
    dependencies:
      react: '*'
  'react-live@*':
    dependencies:
      react: '*'
      '@philpl/buble': '*'
  'react-simple-code-editor@*':
    dependencies:
      react: '*'
  '@lineup-lite/components@*':
    peerDependencies:
      'react-refresh': '*'
  '@lineup-lite/hooks@*':
    peerDependencies:
      'react-refresh': '*'
  '@lineup-lite/table@*':
    peerDependencies:
      'react-refresh': '*'
  'eslint-module-utils@*':
    dependencies:
      eslint-import-resolver-node: '*'
