packageExtensions:
  'prism-react-renderer@*':
    dependencies:
      react: '*'
  'react-live@*':
    dependencies:
      react: '*'
      '@philpl/buble': '*'
  'react-simple-code-editor@*':
    dependencies:
      react: '*'
