blank_issues_enabled: true
contact_links:
  - name: GitHub LineUp-lite Discussions
    url: https://github.com/sgratzl/lineup-lite/discussions
    about: ask question about the library (usage, features,...)
  # - name: Samuel Gratzl
  #   url: https://www.sgratzl.com
  #   about: Please ask and answer questions here.
