name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i -g yarn
      - run: yarn set version berry
      - run: yarn plugin import workspace-tools
      - run: yarn config set checksumBehavior ignore
      - run: cat .yarnrc_patch.yml >> .yarnrc.yml
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ./.yarn
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-
      - run: yarn install
      - run: yarn clean
      - run: yarn build
      - run: yarn lint
      - run: yarn test --ci --coverage --maxWorkers=2
      - run: yarn docs
      - run: |
          mkdir -p public/app
          mv packages/app/dist/* public/app/
          mkdir -p public/api/bundle
          mv packages/bundle/docs/* public/api/bundle/
          mkdir -p public/api/table
          mv packages/table/docs/* public/api/table/

      # - name: Deploy Master
      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      #   uses: upsetjs/actions-gh-pages@sgratzl
      #   with:
      #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #     external_repository: sgratzl/lineup-lite.github.io
      #     publish_branch: master
      #     publish_dir: ./public
      #     enable_jekyll: true
      #     remove_path_spec: 'api/plots/,app/,api/bundle/,api/model/,api/react/'

      # - if: github.ref == 'refs/heads/develop'
      #   # move to next directory
      #   run: |
      #     mv public public2
      #     mkdir -p public
      #     mv public2 public/next

      # - name: Deploy Develop
      #   if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      #   uses: upsetjs/actions-gh-pages@sgratzl
      #   with:
      #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #     external_repository: sgratzl/lineup-lite.github.io
      #     publish_branch: master
      #     publish_dir: ./public
      #     enable_jekyll: true
      #     remove_path_spec: 'next/api/plots/,next/app/,next/api/bundle/,next/api/model/,next/api/react/'

      # - name: Publish
      #   if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
      #   run: |
      #     yarn workspaces foreach --verbose npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
