name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i -g yarn
      - run: yarn set version berry
      - run: yarn plugin import workspace-tools
      - run: yarn config set checksumBehavior ignore
      - run: cat .yarnrc_patch.yml >> .yarnrc.yml
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ./.yarn
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-
      - run: yarn install
      - run: yarn clean
      - run: yarn build
      - run: yarn lint
      - run: yarn test --ci --coverage --maxWorkers=2
      - run: yarn docs
