name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
          key: ${{ runner.os }}-yarn2-v4-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-v4
      - run: yarn install
      - run: yarn clear
      - run: yarn build:packages
      - run: yarn lint
      - run: yarn test:packages --ci --coverage --maxWorkers=2
      - run: yarn docs

  build_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm i -g yarn
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
          key: ${{ runner.os }}-yarn2-v4-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-v4
      - run: yarn install
      - run: yarn clear
      - run: yarn libs
      - run: yarn build:examples
      - run: yarn test:examples --ci --coverage --maxWorkers=2
